# Generated by Django 5.2.5 on 2025-08-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
